### ISSUE TITLE
User de-anonymization through browsing summary report data

### ISSUE THREAD

**Issue by dimitri-xyz** [brave/ledger#3]
_The current version of the documentation is (in my view) not yet sufficiently clear. I had a very hard time making sense of it. So, this is a preliminary assessment. A more formal outline would be useful._

The proposed format of the browsing summary report is: "a list of the top N most visited sites". This summary format suffers from a large sample space. Such list of top N sites would be pulled from a large number of possible sites, i.e. a large sample universe of say 1000 publisher. This can uniquely identify each user. The threat here is not to link a browsing history to a wallet, but to link a browsing history to a real-world identity.

For example, I am Brazilian and thus frequent both publishers with content in English and Portuguese. I am also an avid Haskell enthusiast and go to Haskell.org very frequently. Through examination of the overall universe, it may be possible to determine my browsing history.

There are 1000-choose-20 list in this format, so it may be that many users will have a unique list. To make payments, Brave will have to link real-world identities to wallets (KYC requirements). This knowledge can be used to build a "real-world profile" that can be leveraged to de-anonymize each user's browsing history.

I believe more sophisticated crypto tools may be needed here.

**Comment by mrose17** [comment]
@dimitri-xyz - hi again! i'm not sure i agree.

when the browsing summary is submitted to the ledger, all the ledger knows is that the client is authorized to submit a browsing summary, but the _magic of anonize_ is that we know the request is authorized, but we don't know who (which bitcoin address) submitted the browsing summary.

anonize is very much like an "idealized voting" system -- phase one: you go to the clerk, show your identification, and they hand you a blank ballet and an envelope. phase two: you go into the voting booth, mark the ballet secretly, seal it in an envelope, and drop it in a ballet box. the clerk knows who you are, but (assuming lots of folks are voting at that precinct) the clerk has no idea which ballot goes to which person. the best they can do is know who voted and who didn't, but that's it.

that is what happens when a browsing history is submitted -- phase one: the client does `GET /v1/surveyor/browsing/{surveyorId}/{paymentId}` which returns a cryptographic result that is useful only to the specified `paymentId`. phase two: using that result, the client does `PUT /v1/surveyor/browsing/{surveyorId}` with a payload containing both a cryptographic proof that only someone with the cryptographic secret for `paymentId` can successfully generate and the browsing history. the _magic of anonize_ is that the ledger can verify that the proof is a valid proof, but not which `paymentId` generated it...

does this make sense?

thanks!

/mtr

cc: @abhvious

**Comment by mrose17** [comment]
@dimitri-xyz - i misunderstood. after a conversation with @abhvious, i think i understand the issue you raise, and i agree: "it's a bug!" ... working on a solution! 

best,

/mtr

**Comment by mrose17** [comment]
@dimitri-xyz - hi again!

the ledger has moved to statistical voting: each vote contains one publisher and is independent from all the others in the same reconciliation period. please take a look at https://github.com/brave/ledger/blob/master/documentation/Ledger-Principles.md#ad-free-statistical-voting and the new file https://github.com/brave/ledger/blob/master/documentation/Ledger-Practicals.md and let me know what you think!

many thanks!

**Comment by dimitri-xyz** [comment]
@mrose17 Sorry for the delay. I think this solves the problem! :-)

**Comment by mrose17** [comment]
hooray! many thanks for your patience and double many thanks for your counsel and help!
